services:
  - type: web
    name: iq-demo
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_STRING
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
